name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install django python-dotenv dj-database-url gunicorn psycopg2-binary django-bootstrap5 coverage flake8 rollbar
      - name: Run test coverage
        run: |
          python -m coverage run --source=task_manager manage.py test
          python -m coverage xml
      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=starbuck007_python-project-52
            -Dsonar.organization=starbuck007
            -Dsonar.python.coverage.reportPaths=coverage.xml
